### ISSUE TITLE
[K8SPSMDB-203] Add support for cluster-wide operators

### ISSUE THREAD

**Issue by spron-in** [percona/roadmap#42] opened 2021-05-12 13:28 UTC
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about the feature**
Our operator design right now requires one operator per namespace, we still want this to be our default behavior, but it's a highly requested features from customers, partners, and community members to support a single operator for many namespaces.  We should validate the capability and enabled it in how we initialize the operator with the Operator Framework SDK.

**Comment by dalbani** [comment] 2021-09-27 09:29
How does do this relate to https://github.com/percona/roadmap/issues/28?

**Comment by mrszop** [comment] 2022-06-02 13:13
Hello peops,

any news on this topic? "I would like to setup a single percona-server-mongodb-operator deployment watching all namespaces for CRD PerconaServerMongoDB in my k8s cluster."

Cheers

**Comment by jconradhanson** [comment] 2022-08-08 13:02
@spron-in Now that #28 has been closed due to being a duplicate of this issue, do we still have confidence that cluster-wide support for PSMDB Operator will be implemented in release `1.13.0` according to [this comment](https://github.com/percona/roadmap/issues/28#issuecomment-1206136770) on the closed issue?

**Closed** 2022-09-27 13:01 UTC
Labels: Operators, MongoDB, 1.13.0
